// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SniffleReport.Api.Data;

#nullable disable

namespace SniffleReport.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404183141_AddRegionSnapshots")]
    partial class AddRegionSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogEntries", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.CostTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuideId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("CostTiers", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.DiseaseTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<int>("CaseCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IngestedRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("SourceDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IngestedRecordId");

                    b.HasIndex("AlertId", "Date")
                        .HasDatabaseName("IX_DiseaseTrend_AlertId_Date");

                    b.ToTable("DiseaseTrends", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FactCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Verdict")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId")
                        .IsUnique();

                    b.ToTable("FactChecks", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FactCheckHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactCheckId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("FactCheckId");

                    b.ToTable("FactCheckHistories", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FeedSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("boolean");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSyncStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("PollingInterval")
                        .HasColumnType("interval");

                    b.Property<string>("SoqlQuery")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "LastSyncStartedAt")
                        .HasDatabaseName("IX_FeedSource_IsEnabled_LastSyncStartedAt");

                    b.ToTable("FeedSources", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FeedSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertsPromoted")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text");

                    b.Property<Guid>("FeedSourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsFetched")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsSkippedDuplicate")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsSkippedUnmappable")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("FeedSourceId", "StartedAt")
                        .HasDatabaseName("IX_FeedSyncLog_FeedSourceId_StartedAt");

                    b.ToTable("FeedSyncLogs", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.HealthAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaseCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("IngestedRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceAttribution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("SourceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IngestedRecordId");

                    b.HasIndex("RegionId", "CreatedAt")
                        .HasDatabaseName("IX_HealthAlert_RegionId_CreatedAt");

                    b.ToTable("HealthAlerts", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.IngestedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FeedSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstIngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IngestCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastIngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("FeedSourceId", "ExternalSourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_IngestedRecord_FeedSourceId_ExternalSourceId");

                    b.ToTable("IngestedRecords", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.LocalResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("HoursJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServicesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "Type")
                        .HasDatabaseName("IX_LocalResource_RegionId_Type");

                    b.ToTable("LocalResources", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("IngestedRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IngestedRecordId");

                    b.HasIndex("RegionId", "PublishedAt")
                        .HasDatabaseName("IX_NewsItem_RegionId_PublishedAt");

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.PreventionGuide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("PreventionGuides", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.RegionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewsHighlightsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PreventionHighlightsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PublishedAlertCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceCountsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TopAlertsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TrendHighlightsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ComputedAt")
                        .HasDatabaseName("IX_RegionSnapshot_ComputedAt");

                    b.HasIndex("RegionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RegionSnapshot_RegionId");

                    b.ToTable("RegionSnapshots", (string)null);
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.CostTier", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.PreventionGuide", "Guide")
                        .WithMany("CostTiers")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.DiseaseTrend", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.HealthAlert", "Alert")
                        .WithMany("DiseaseTrends")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SniffleReport.Api.Models.Entities.IngestedRecord", "IngestedRecord")
                        .WithMany()
                        .HasForeignKey("IngestedRecordId");

                    b.Navigation("Alert");

                    b.Navigation("IngestedRecord");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FactCheck", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.NewsItem", "NewsItem")
                        .WithOne("FactCheck")
                        .HasForeignKey("SniffleReport.Api.Models.Entities.FactCheck", "NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FactCheckHistory", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.FactCheck", "FactCheck")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("FactCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactCheck");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FeedSyncLog", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.FeedSource", "FeedSource")
                        .WithMany("SyncLogs")
                        .HasForeignKey("FeedSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedSource");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.HealthAlert", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.IngestedRecord", "IngestedRecord")
                        .WithMany()
                        .HasForeignKey("IngestedRecordId");

                    b.HasOne("SniffleReport.Api.Models.Entities.Region", "Region")
                        .WithMany("HealthAlerts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestedRecord");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.IngestedRecord", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.FeedSource", "FeedSource")
                        .WithMany("IngestedRecords")
                        .HasForeignKey("FeedSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedSource");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.LocalResource", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.Region", "Region")
                        .WithMany("LocalResources")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.NewsItem", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.IngestedRecord", "IngestedRecord")
                        .WithMany()
                        .HasForeignKey("IngestedRecordId");

                    b.HasOne("SniffleReport.Api.Models.Entities.Region", "Region")
                        .WithMany("NewsItems")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestedRecord");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.PreventionGuide", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.Region", "Region")
                        .WithMany("PreventionGuides")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.Region", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.Region", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.RegionSnapshot", b =>
                {
                    b.HasOne("SniffleReport.Api.Models.Entities.Region", "Region")
                        .WithOne()
                        .HasForeignKey("SniffleReport.Api.Models.Entities.RegionSnapshot", "RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FactCheck", b =>
                {
                    b.Navigation("HistoryEntries");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.FeedSource", b =>
                {
                    b.Navigation("IngestedRecords");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.HealthAlert", b =>
                {
                    b.Navigation("DiseaseTrends");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.NewsItem", b =>
                {
                    b.Navigation("FactCheck");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.PreventionGuide", b =>
                {
                    b.Navigation("CostTiers");
                });

            modelBuilder.Entity("SniffleReport.Api.Models.Entities.Region", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("HealthAlerts");

                    b.Navigation("LocalResources");

                    b.Navigation("NewsItems");

                    b.Navigation("PreventionGuides");
                });
#pragma warning restore 612, 618
        }
    }
}
